version: '3.1'

services: 
    drupal:
        image: drupal
        ports:
         - 8888:80 # 88888 browser side port 80 is container port
        volumes: 
           - drupal-modules:/var/www/html/modules
           - drupal-profiles:/var/www/html/profiles
           - drupal-sites:/var/www/html/sites
           - drupal-themes:/var/www/html/themes
    
    postgres:
        image: postgres
        environment: 
            - POSTGRES_PASSWORD=pass
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres # need for advanced settings 

volumes: 
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:



#docker-compose down delete every thing
#######!USE!######
#dokcer-compose stop 
